name: ci-cd
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Maker login to Docker Hub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_PWD }}

    - name: Build and push:Z
      uses: docker/build-push-action@v2
      with:
        context: ./src
        file: ./src/Dockerfile
        push: true
        tags: |
          amatildes/rotten-potatoes:latest
          amatildes/rotten-potatoes:${{github.run_number}}
  cd:
    needs: ci
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Verificando credencias AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Configure and update context
      run: aws eks update-kubeconfig --name stg --region us-east-1

    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/v1.20.0/bin/linux/amd64/kubectl
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/

    - name: Deployment in the Development cluster
      run: kubectl apply -f k8s/deployment.yaml